/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        /* Official Workshop Pro brand palette */
        brand: {
          charcoal: '#141413',
          parchment: '#faf9f5',
          terracotta: '#C15F3C',
          'terracotta-light': '#d97757',
          mid: '#b0aea5',
          light: '#e8e6dc',
          white: '#ffffff',
          success: '#5a7a52',
          'success-bg': '#e8ede6',
          error: '#a04a2f',
          'error-bg': '#f5ebe8',
          warning: '#b8860b',
          'warning-bg': '#f5f0e6',
          'dark-hover': '#1f1e1d',
          'dark-border': '#2a2928',
        },
        /* Semantic tokens (maps to brand — used across components) */
        claude: {
          bg: '#faf9f5',
          surface: '#e8e6dc',
          card: '#ffffff',
          hover: '#e8e6dc',
          elevated: '#e0ddd4',
          border: '#b0aea5',
          'border-focus': '#C15F3C',
          text: '#141413',
          'text-muted': '#b0aea5',
          'text-subtle': '#b0aea5',
          accent: '#C15F3C',
          'accent-shimmer': '#d97757',
          'accent-dim': '#a04d32',
          success: '#5a7a52',
          'success-dim': '#e8ede6',
          error: '#a04a2f',
          'error-dim': '#f5ebe8',
          warning: '#b8860b',
          'warning-dim': '#f5f0e6',
          plan: '#6b8f9e',
          dark: '#141413',
          'dark-text': '#faf9f5',
          'dark-muted': '#b0aea5',
          'dark-hover': '#1f1e1d',
          'dark-border': '#2a2928',
        },
        workshop: {
          black: '#141413',
          darker: '#141413',
          dark: '#e8e6dc',
          card: '#ffffff',
          border: '#b0aea5',
          muted: '#b0aea5',
          blue: '#C15F3C',
          'blue-light': '#d97757',
          accent: '#d97757',
          success: '#5a7a52',
          warning: '#b8860b',
          danger: '#a04a2f',
        },
      },
      fontFamily: {
        sans: [
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          'sans-serif',
        ],
        mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Consolas', 'monospace'],
      },
      boxShadow: {
        glow: '0 0 20px rgba(193, 95, 60, 0.18)',
        card: '0 1px 2px rgba(20, 20, 19, 0.06), 0 4px 16px rgba(20, 20, 19, 0.04)',
        'card-hover': '0 4px 20px rgba(20, 20, 19, 0.08)',
        sidebar: '2px 0 12px rgba(20, 20, 19, 0.06)',
      },
      borderRadius: {
        brand: '10px',
      },
      animation: {
        'fade-in': 'fadeIn 0.2s ease-out',
        'slide-up': 'slideUp 0.25s ease-out',
      },
      keyframes: {
        fadeIn: { from: { opacity: '0' }, to: { opacity: '1' } },
        slideUp: { from: { opacity: '0', transform: 'translateY(8px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
      },
    },
  },
  plugins: [],
};
